### ISSUE TITLE
Issue on first run

### ISSUE THREAD

**Issue by gnompsky** [Idnan/git-random#1]
On first run there is no last user id in local storage which causes the usersUrl to be populated as "...usersaccess_token=..." instead of "...users**_?_**access_token=...".

Fix is below:

git_random.js line 27 reads:
`usersUrl += (getLastUserId() !== false) ? "?since=" + getLastUserId() + "&" + token : token;`
whereas it should read:
`usersUrl += (getLastUserId() !== false) ? "?since=" + getLastUserId() + "&" + token : "?" + token;`

Sorry would have added a pull request but I'm not at my PC. Nice extension though :)

**Comment by Idnan** [comment]
Fixed. Thanks :)
